
# Author: Giovanni Rasera

v1:
	if [ -d "./build" ]; then rm -r build; fi
	mkdir build
	
	# from cuda documentation
	g++ -o ./build/$@.out ./$@.cpp -std=c++23

	./build/$@.out

v2:
	if [ -d "./build" ]; then rm -r build; fi
	mkdir build
	
	# from cuda documentation
	g++ -o ./build/$@.out ./$@.cpp -std=c++23

	./build/$@.out
