# Author: Giovanni Rasera
cpu:
	#if [ -d "./build" ]; then rm -r build; fi
	#mkdir build
	g++ -o ./build/$@_sequential.out ./$@.cpp -std=c++23
p:
	git add . && git commit -m "automatic: data exchange" && git push